-- Inserção da lista de serviços de costuraria com preços base

INSERT INTO services (name, description, base_price, category) VALUES
  ('Barra gode c/ forro', NULL, 140.00, 'costuraria'),
  ('Barra gode (crinol ou revel)', NULL, 180.00, 'costuraria'),
  ('Barra cortada + forro', 'A partir de R$ 120,00', 120.00, 'costuraria'),
  ('Barra cortada', NULL, 100.00, 'costuraria'),
  ('Barra gode', 'A partir de R$ 120,00', 120.00, 'costuraria'),
  ('Alças embutida', 'A partir de R$ 45,00', 45.00, 'costuraria'),
  ('Ajuste lateral c/ forro', 'A partir de R$ 80,00', 80.00, 'costuraria'),
  ('Ajuste lateral sem forro', NULL, 60.00, 'costuraria'),
  ('Colocar bojo', 'A partir de R$ 45,00', 45.00, 'costuraria'),
  ('Fazer pence', 'A partir de R$ 35,00', 35.00, 'costuraria'),
  ('Ajuste c/ zíper', 'A partir de R$ 120,00', 120.00, 'costuraria'),
  ('Ajuste com pedraria tirando e recolocando', 'A partir de R$ 220,00', 220.00, 'costuraria'),
  ('Combo ajuste simples c/ barra', 'A partir de R$ 80,00', 80.00, 'costuraria'),
  ('Combo forrado c/ barra', 'A partir de R$ 120,00', 120.00, 'costuraria'),
  ('Customização', 'A partir de R$ 180,00', 180.00, 'costuraria'),
  ('Barra simples', NULL, 40.00, 'costuraria'),
  ('Barra original', NULL, 50.00, 'costuraria'),
  ('Barra postiça', NULL, 55.00, 'costuraria'),
  ('Barra italiana', NULL, 45.00, 'costuraria'),
  ('Barra c/ fenda', 'A partir de R$ 45,00', 45.00, 'costuraria'),
  ('Barra pantalona', 'A partir de R$ 40,00', 40.00, 'costuraria'),
  ('Barra gaboneira', NULL, 40.00, 'costuraria'),
  ('Barra jaqueta c/ zíper', NULL, 90.00, 'costuraria'),
  ('Barra e funelar', NULL, 70.00, 'costuraria'),
  ('Barra manga malha', NULL, 35.00, 'costuraria'),
  ('Barra de camisa c/ punho c/casinha', NULL, 75.00, 'costuraria'),
  ('Barra babado tirando por cima', 'A partir de R$ 80,00', 80.00, 'costuraria'),
  ('Barra com elástico embutido', 'A partir de R$ 80,00', 80.00, 'costuraria'),
  ('Barra reta', NULL, 70.00, 'costuraria'),
  ('Barra larga', NULL, 60.00, 'costuraria'),
  ('Barra c/ punho simples', NULL, 40.00, 'costuraria'),
  ('Barra c/ punho forrado', NULL, 65.00, 'costuraria'),
  ('Barra de blazer c/ botão canto mitrado', NULL, 90.00, 'costuraria'),
  ('Barra no corte', 'A partir de R$ 60,00', 60.00, 'costuraria'),
  ('Cos em geral', NULL, 45.00, 'costuraria'),
  ('Combo cos e lateral', NULL, 55.00, 'costuraria'),
  ('Combo cos e lateral c/ forro', NULL, 65.00, 'costuraria'),
  ('Combo barra lateral', NULL, 80.00, 'costuraria'),
  ('Combo cos e barra', NULL, 70.00, 'costuraria'),
  ('Barra e cava', 'A partir de R$ 45,00 até R$ 120,00', 45.00, 'costuraria'),
  ('Barra invisível', NULL, 45.00, 'costuraria'),
  ('Cós largo / cava', 'A partir de R$ 60,00 até R$ 120,00', 60.00, 'costuraria'),
  ('Troca de tecido ou comprimento no cós', 'A partir de R$ 60,00', 60.00, 'costuraria'),
  ('Troca de elástico no cós', 'A partir de R$ 40,00', 40.00, 'costuraria');
